export const metadata = { title: "Risk disclaimer · TradeReady" };

export default function RiskDisclaimerPage() {
  return (
    <div className="legal-shell">
      <h1>Risk disclaimer</h1>
      <p className="legal-draft">
        <strong>Draft — review with a lawyer before launch.</strong>
      </p>

      <p>
        TradeReady is an educational tool for learning trading discipline. It is <strong>not</strong> a
        registered investment adviser, broker, or financial planner. Nothing in this app is personalized
        investment, legal, tax, or financial advice.
      </p>

      <h2>Trading involves substantial risk</h2>
      <p>
        Trading stocks, options, and crypto can result in significant financial loss, including the loss
        of your entire investment. Past performance does not guarantee future results. You are solely
        responsible for any decisions you make based on information shown in this app, including AI-generated
        signals, grades, and recommendations.
      </p>

      <h2>What this app does and doesn't do</h2>
      <p>
        TradeReady connects to your own brokerage account (currently Alpaca paper) at your direction.
        Orders you place through TradeReady are executed by your broker, not by TradeReady. We do not hold,
        manage, or have custody of any funds.
      </p>

      <h2>Automation and signals</h2>
      <p>
        Any signal, recommendation, or "auto-stop" feature is generated by software and can be wrong.
        Markets can gap past stops. You must monitor your own positions and accept that the software may
        fail, lose connectivity, or generate incorrect signals.
      </p>

      <h2>Acknowledgment</h2>
      <p>
        By using this app you acknowledge that you understand these risks, that you alone are responsible
        for your trades, and that TradeReady, its operators, and its contributors will not be liable for
        any losses you incur.
      </p>
    </div>
  );
}
